services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ConnectionStrings__Postgres: ${DB_CONNECTION}
      Redis__Connection: redis:6379
      Jwt__Issuer: WeatherIntel
      Jwt__Audience: WeatherIntel
      Jwt__AccessTokenMinutes: 15
      JWT_SECRET: ${JWT_SECRET}
      RateLimits__WeatherPerMinute: 10
      RateLimits__InsightsPerMinute: 2
      OpenAI__ApiKey: ${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: weather
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
